### ISSUE TITLE
Links to the documentation are incorrect.

### ISSUE THREAD

**Issue by thooijer63** [Mellow-3D/Fly-SB2040#1]
https://github.com/Mellow-3D/Fly-SB2040#readme 
go to Fly-SB2040
Information about the Fly-SB2040 for voron

The board can be purchased from here https://www.aliexpress.com/item/1005004675264551.html

More information can be found here http://mellow.klipper.cn/?spm=a2g0o.detail.1000023.17.73937885EgBMV3#/board/fly_sht36_42/
The link in the readme and also the links on aliexpress are incorrect,
Please correct this as the fly_sht36_42 is not the Fly-SB2040..

**Comment by jaysuk** [comment]
updated link
