### ISSUE TITLE
V2 - Schematic and model

### ISSUE THREAD

**Issue by flemish4** [Mellow-3D/Fly-SB2040#8]
Hi,

I have just purchased a Fly-SB2040 and the board says it is V2. Would it be possible to update this repo for the new version?
It also has an extra 4 pin connector, and an unpopulated 20-pin pad on the back and I wanted to know what these are for?

**Comment by jaysuk** [comment]
They're for a PT100 and a MAX31865

**Comment by rbrtwtrs** [comment]
I would also like the update for V2.

**Comment by jaysuk** [comment]
Added the schematic
